#!/bin/bash
# README
# 
# Little script to process each request/response pair
# generated by justniffer.
#
# Each pair is output with one line;
# This script saves the lines into file for later processing.
#
# File name is give by the $1 parameter
#
# by chenxm
# 2013-01

read line;
echo $line >> $1

exit 0;